--------------------------------------------------------
-- Archivo creado  - lunes-agosto-14-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTE
--------------------------------------------------------


CREATE USER NTTDATA1 IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;


GRANT CREATE TABLE , CREATE SESSION, CREATE VIEW , CREATE ANY TRIGGER, CREATE ANY PROCEDURE, CREATE SEQUENCE TO NTTDATA1;



   CREATE SEQUENCE  "NTTDATA1"."SEQ_CLIENTE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CUENTA
--------------------------------------------------------

   CREATE SEQUENCE  "NTTDATA1"."SEQ_CUENTA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVIMIENTOS
--------------------------------------------------------

   CREATE SEQUENCE  "NTTDATA1"."SEQ_MOVIMIENTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PROD
--------------------------------------------------------

   CREATE SEQUENCE  "NTTDATA1"."SEQ_PROD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "NTTDATA1"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(4,0), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"ESTADO" CHAR(1 BYTE) DEFAULT 1, 
	"NOMBRES" VARCHAR2(120 BYTE), 
	"GENERO" VARCHAR2(20 BYTE), 
	"NUM_DOC" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"TIPO_DOC" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "NTTDATA1"."CUENTA" 
   (	"ID_CUENTA" NUMBER(4,0), 
	"NUM_CUENTA" VARCHAR2(20 BYTE), 
	"TIP_CUENTA" VARCHAR2(50 BYTE), 
	"SALDO_INIT" NUMBER(*,0), 
	"ESTADO" CHAR(1 BYTE) DEFAULT 1, 
	"ID_CLIENTE" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "NTTDATA1"."MOVIMIENTOS" 
   (	"ID_MOVIMIENTO" NUMBER(4,0), 
	"FECHA_MOV" DATE DEFAULT SYSDATE, 
	"TIP_MOV" VARCHAR2(50 BYTE), 
	"VALOR" NUMBER(*,0), 
	"SALDO" NUMBER(*,0), 
	"ID_CUENTA" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index CLIENTE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTTDATA1"."CLIENTE_UK1" ON "NTTDATA1"."CLIENTE" ("NUM_DOC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007159
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTTDATA1"."SYS_C007159" ON "NTTDATA1"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007165
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTTDATA1"."SYS_C007165" ON "NTTDATA1"."CUENTA" ("ID_CUENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007169
--------------------------------------------------------

  CREATE UNIQUE INDEX "NTTDATA1"."SYS_C007169" ON "NTTDATA1"."MOVIMIENTOS" ("ID_MOVIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "NTTDATA1"."CLIENTE" ADD CONSTRAINT "CLIENTE_UK1" UNIQUE ("NUM_DOC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("NUM_DOC" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CLIENTE" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "NTTDATA1"."CUENTA" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CUENTA" ADD PRIMARY KEY ("ID_CUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NTTDATA1"."CUENTA" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CUENTA" MODIFY ("TIP_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CUENTA" MODIFY ("NUM_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."CUENTA" MODIFY ("ID_CUENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" MODIFY ("ID_CUENTA" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" MODIFY ("SALDO" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" ADD PRIMARY KEY ("ID_MOVIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" MODIFY ("TIP_MOV" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" MODIFY ("FECHA_MOV" NOT NULL ENABLE);
  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" MODIFY ("ID_MOVIMIENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CUENTA
--------------------------------------------------------

  ALTER TABLE "NTTDATA1"."CUENTA" ADD CONSTRAINT "CUENTA_CLIENTE_FK" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "NTTDATA1"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MOVIMIENTOS
--------------------------------------------------------

  ALTER TABLE "NTTDATA1"."MOVIMIENTOS" ADD CONSTRAINT "MOVIMIENTO_CUENTA_FK" FOREIGN KEY ("ID_CUENTA")
	  REFERENCES "NTTDATA1"."CUENTA" ("ID_CUENTA") ENABLE;


commit;